# Generated by Django 5.0.1 on 2024-01-24 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("birth_date", models.DateField()),
                ("cc", models.CharField(max_length=11)),
                ("address", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=5)),
                ("complement", models.CharField(max_length=30)),
                ("local", models.CharField(max_length=30)),
                ("nif", models.CharField(max_length=8)),
                ("city", models.CharField(max_length=30)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("AV", "Aveiro"),
                            ("BJ", "Beja"),
                            ("BR", "Braga"),
                            ("BG", "Bragança"),
                            ("CA", "Castelo Branco"),
                            ("CB", "Coimbra"),
                            ("EV", "Évora"),
                            ("FA", "Faro"),
                            ("PO", "Portalegre"),
                            ("SA", "Santarém"),
                            ("SE", "Setúbal"),
                            ("VR", "Vila Real"),
                            ("VI", "Viseu"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "UserProfile",
                "verbose_name_plural": "UserProfiles",
            },
        ),
    ]
