# Generated by Django 5.0.1 on 2024-01-24 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_description", models.TextField(max_length=255)),
                ("long_description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/images/%Y/%m"
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("marketing_price", models.FloatField(verbose_name="Price")),
                (
                    "marketing_price_promotion",
                    models.FloatField(default=0, verbose_name="Price Promo."),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("V", "Variable"), ("S", "Simple")],
                        default="V",
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("price", models.FloatField()),
                ("promotion_price", models.FloatField(default=0)),
                ("stock", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variation",
                "verbose_name_plural": "Variations",
            },
        ),
    ]
