# Generated by Django 5.0.1 on 2024-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.PositiveIntegerField(),
        ),
    ]
