# Generated by Django 5.0.1 on 2024-01-30 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total",
            new_name="qtd_total",
        ),
    ]
