# Generated by Django 5.0.1 on 2024-01-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_rename_total_order_qtd_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
